HOST: "localhost"
PORT: "1321"

DB:
  DIALECT: "postgres"
  URL: ""
  NAME: "promotions"
  USER: "postgres"
  PASSWORD: "goodkat1453"
  HOST: "localhost"
  PORT: "5432"
  PROPERTIES:
    MaxOpenConnections: 50
    MaxIdleConnections: 10
    ConnMaxIdleTime: 100